spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100
      datasource:
        driver-class-name: org.postgresql.Driver
